import type { MarketMeta, PageConfig, PageKey } from "../types";

export const pages: Record<PageKey, PageConfig> = {
  system: {
    title: "仪表盘",
    subtitle: "实时查看本机开发环境状态",
  },
  tools: {
    title: "环境市场",
    subtitle: "卡片式管理开发工具，支持筛选与一键安装",
  },
  docker: {
    title: "Docker",
    subtitle: "保留现有命令并优化交互体验",
  },
  settings: {
    title: "设置",
    subtitle: "主题、安装偏好与体验配置",
  },
};

export const marketMetaMap: Record<string, MarketMeta> = {
  "nodejs-lts": {
    title: "Node.js 开发环境",
    description: "完整 Node.js LTS 环境，适合前端与全栈开发。",
    tags: ["#javascript", "#web"],
    hot: "12400",
    downloads: "5000万+",
    type: "Language",
  },
  python: {
    title: "Python 数据科学",
    description: "Python 3.12 工具链，适配脚本、数据处理与 AI。",
    tags: ["#ai", "#data"],
    hot: "8900",
    downloads: "2200万+",
    type: "Language",
  },
  go: {
    title: "Go 微服务",
    description: "面向高性能后端服务的 Go 语言开发环境。",
    tags: ["#backend", "#fast"],
    hot: "7600",
    downloads: "1200万+",
    type: "Language",
  },
  rustup: {
    title: "Rust 系统开发",
    description: "Rust + Cargo 完整工具链，适合桌面与系统工具。",
    tags: ["#systems", "#performance"],
    hot: "9800",
    downloads: "1800万+",
    type: "Language",
  },
  "docker-desktop": {
    title: "Docker 容器环境",
    description: "Docker Desktop 及 Compose 生态，一键容器化开发。",
    tags: ["#container", "#devops"],
    hot: "15000",
    downloads: "1亿+",
    type: "Container",
  },
  kubectl: {
    title: "Kubernetes 客户端",
    description: "K8s 集群命令行管理工具，适配云原生开发流程。",
    tags: ["#k8s", "#cloud"],
    hot: "6300",
    downloads: "900万+",
    type: "Container",
  },
  postgresql: {
    title: "PostgreSQL 数据库",
    description: "主流开源关系型数据库，适合事务型业务场景。",
    tags: ["#sql", "#db"],
    hot: "15000",
    downloads: "1亿+",
    type: "Database",
  },
  mysql: {
    title: "MySQL 数据库",
    description: "经典关系型数据库，广泛用于 Web 应用与 SaaS。",
    tags: ["#sql", "#web"],
    hot: "13200",
    downloads: "9000万+",
    type: "Database",
  },
  "mongodb-shell": {
    title: "MongoDB 工具",
    description: "文档型数据库命令行工具，适合非结构化数据场景。",
    tags: ["#nosql", "#json"],
    hot: "11000",
    downloads: "8000万+",
    type: "Database",
  },
  "dotnet-sdk": {
    title: ".NET 开发包",
    description: "跨平台 .NET SDK，支持 Web/API/桌面多场景开发。",
    tags: ["#dotnet", "#backend"],
    hot: "7200",
    downloads: "1700万+",
    type: "Language",
  },
  vscode: {
    title: "VS Code",
    description: "轻量但强大的代码编辑器，适配多语言开发工作流。",
    tags: ["#editor", "#ide"],
    hot: "20000",
    downloads: "2亿+",
    type: "IDE",
  },
  "aws-cli": {
    title: "AWS CLI",
    description: "AWS 云资源命令行工具，适合云端自动化与运维。",
    tags: ["#cloud", "#devops"],
    hot: "7800",
    downloads: "1200万+",
    type: "Cloud",
  },
  "azure-cli": {
    title: "Azure CLI",
    description: "Microsoft Azure 命令行工具，适配云原生部署流程。",
    tags: ["#cloud", "#azure"],
    hot: "7200",
    downloads: "900万+",
    type: "Cloud",
  },
  "gcloud-cli": {
    title: "Google Cloud CLI",
    description: "Google Cloud 管理工具链，适合多云开发环境。",
    tags: ["#cloud", "#gcp"],
    hot: "6900",
    downloads: "800万+",
    type: "Cloud",
  },
  flutter: {
    title: "Flutter",
    description: "跨平台移动端与桌面 UI 框架，覆盖 Android/iOS/Desktop。",
    tags: ["#mobile", "#crossplatform"],
    hot: "9800",
    downloads: "1500万+",
    type: "Mobile",
  },
  dart: {
    title: "Dart SDK",
    description: "Flutter 与服务端开发常用语言工具链。",
    tags: ["#mobile", "#language"],
    hot: "6400",
    downloads: "700万+",
    type: "Language",
  },
  "android-platform-tools": {
    title: "Android Platform Tools",
    description: "ADB/Fastboot 工具集，适配 Android 真机调试。",
    tags: ["#android", "#debug"],
    hot: "8300",
    downloads: "1300万+",
    type: "Mobile",
  },
  cmake: {
    title: "CMake",
    description: "跨平台构建系统，适配 C/C++ 与混合工程。",
    tags: ["#cpp", "#build"],
    hot: "9100",
    downloads: "3000万+",
    type: "Build",
  },
  sqlite: {
    title: "SQLite",
    description: "轻量级嵌入式数据库，适合本地工具与离线应用。",
    tags: ["#database", "#embedded"],
    hot: "8600",
    downloads: "5000万+",
    type: "Database",
  },
  "android-studio": {
    title: "Android Studio",
    description: "Android 官方 IDE，适合原生移动端开发。",
    tags: ["#android", "#ide"],
    hot: "11200",
    downloads: "1亿+",
    type: "IDE",
  },
};
