#[derive(Clone, Copy)]
pub struct ToolSpec {
    pub name: &'static str,
    pub command: &'static str,
    pub args: &'static [&'static str],
    pub category: &'static str,
    pub install_key: Option<&'static str>,
}

pub fn default_tool_specs() -> Vec<ToolSpec> {
    vec![
        ToolSpec { name: "Node.js", command: "node", args: &["-v"], category: "Runtime", install_key: Some("nodejs-lts") },
        ToolSpec { name: "npm", command: "npm", args: &["-v"], category: "Package", install_key: Some("nodejs-lts") },
        ToolSpec { name: "pnpm", command: "pnpm", args: &["-v"], category: "Package", install_key: Some("pnpm") },
        ToolSpec { name: "Yarn", command: "yarn", args: &["-v"], category: "Package", install_key: Some("yarn") },
        ToolSpec { name: "Bun", command: "bun", args: &["--version"], category: "Runtime", install_key: Some("bun") },
        ToolSpec { name: "Deno", command: "deno", args: &["--version"], category: "Runtime", install_key: Some("deno") },
        ToolSpec { name: "Python", command: "python", args: &["--version"], category: "Language", install_key: Some("python") },
        ToolSpec { name: "pip", command: "pip", args: &["--version"], category: "Package", install_key: Some("python") },
        ToolSpec { name: "pipx", command: "pipx", args: &["--version"], category: "Package", install_key: Some("pipx") },
        ToolSpec { name: "uv", command: "uv", args: &["--version"], category: "Package", install_key: Some("uv") },
        ToolSpec { name: "Conda", command: "conda", args: &["--version"], category: "Runtime", install_key: Some("miniconda") },
        ToolSpec { name: "Go", command: "go", args: &["version"], category: "Language", install_key: Some("go") },
        ToolSpec { name: "Java", command: "java", args: &["-version"], category: "Language", install_key: Some("openjdk") },
        ToolSpec { name: "Javac", command: "javac", args: &["-version"], category: "Language", install_key: Some("openjdk") },
        ToolSpec { name: "Maven", command: "mvn", args: &["-version"], category: "Build", install_key: Some("maven") },
        ToolSpec { name: "Gradle", command: "gradle", args: &["-v"], category: "Build", install_key: Some("gradle") },
        ToolSpec { name: "Rust", command: "rustc", args: &["--version"], category: "Language", install_key: Some("rustup") },
        ToolSpec { name: "Cargo", command: "cargo", args: &["--version"], category: "Build", install_key: Some("rustup") },
        ToolSpec { name: "Git", command: "git", args: &["--version"], category: "SCM", install_key: Some("git") },
        ToolSpec { name: "GitHub CLI", command: "gh", args: &["--version"], category: "SCM", install_key: Some("gh") },
        ToolSpec { name: "Docker", command: "docker", args: &["--version"], category: "Container", install_key: Some("docker-desktop") },
        ToolSpec { name: "Docker Compose", command: "docker", args: &["compose", "version"], category: "Container", install_key: Some("docker-desktop") },
        ToolSpec { name: "kubectl", command: "kubectl", args: &["version", "--client"], category: "Container", install_key: Some("kubectl") },
        ToolSpec { name: "Helm", command: "helm", args: &["version"], category: "Container", install_key: Some("helm") },
        ToolSpec { name: "Terraform", command: "terraform", args: &["-version"], category: "IaC", install_key: Some("terraform") },
        ToolSpec { name: ".NET SDK", command: "dotnet", args: &["--version"], category: "Language", install_key: Some("dotnet-sdk") },
        ToolSpec { name: "PowerShell", command: "pwsh", args: &["--version"], category: "Shell", install_key: Some("powershell") },
        ToolSpec { name: "VS Code", command: "code", args: &["--version"], category: "IDE", install_key: Some("vscode") },
        ToolSpec { name: "AWS CLI", command: "aws", args: &["--version"], category: "Cloud", install_key: Some("aws-cli") },
        ToolSpec { name: "Azure CLI", command: "az", args: &["--version"], category: "Cloud", install_key: Some("azure-cli") },
        ToolSpec { name: "Google Cloud CLI", command: "gcloud", args: &["--version"], category: "Cloud", install_key: Some("gcloud-cli") },
        ToolSpec { name: "Flutter", command: "flutter", args: &["--version"], category: "Mobile", install_key: Some("flutter") },
        ToolSpec { name: "Dart", command: "dart", args: &["--version"], category: "Language", install_key: Some("dart") },
        ToolSpec { name: "ADB", command: "adb", args: &["version"], category: "Mobile", install_key: Some("android-platform-tools") },
        ToolSpec { name: "CMake", command: "cmake", args: &["--version"], category: "Build", install_key: Some("cmake") },
        ToolSpec { name: "SQLite CLI", command: "sqlite3", args: &["--version"], category: "Database", install_key: Some("sqlite") },
        ToolSpec { name: "PostgreSQL CLI", command: "psql", args: &["--version"], category: "Database", install_key: Some("postgresql") },
        ToolSpec { name: "MySQL CLI", command: "mysql", args: &["--version"], category: "Database", install_key: Some("mysql") },
        ToolSpec { name: "MongoDB Shell", command: "mongosh", args: &["--version"], category: "Database", install_key: Some("mongodb-shell") },
        ToolSpec { name: "Redis CLI", command: "redis-cli", args: &["--version"], category: "Database", install_key: Some("redis") },
        ToolSpec { name: "Claude Code", command: "claude", args: &["--version"], category: "AI", install_key: Some("claude-code") },
        ToolSpec { name: "Codex CLI", command: "codex", args: &["--version"], category: "AI", install_key: Some("codex-cli") },
        ToolSpec { name: "Gemini CLI", command: "gemini", args: &["--version"], category: "AI", install_key: Some("gemini-cli") },
    ]
}
